spring.application.name=proyectos

#CONEXION A POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/proyectos_db

spring.datasource.username=postgres

spring.datasource.password=Barcelonac10


#DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver

#HIBERNATE CREA Y ACTUALIZA TABLAS AUTOMATICAMENTE 
spring.jpa.hibernate.ddl-auto=update

#MOSTRAR SQL EN CONSOLA
spring.jpa.show-sql=true

#FORMATEAR SQL
spring.jpa.properties.hibernate.format_sql=true

#LOGS DE SPRING
logging.level.org.springframework=INFO

#LOGS DE HIBERNATE SQL
logging.level.org.hibernate.SQL=DEBUG

#MOSTRAR PARAMETROS DE SQL
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.springframework.web=DEBUG

logging.level.org.springframework.http.converter.json=DEBUG

# JWT
jwt.secret=MiClaveSuperSeguraParaElProyectoBackend2026JWT123456789
jwt.expiration=86400000